add hw2
Sango-dev/Nix11 pull request #1
Opened 2022-07-09 11:09 UTC by Sango-dev

2022-07-11 22:05 UTC, Fabolo12 requested changes
java: package lombok does not exist

2022-07-12 08:09 UTC, Sango-dev commented
> java: package lombok does not exist

2022-07-16 19:58 UTC, Fabolo12 approved these changes

2022-07-16 19:58 UTC, Fabolo12 commented on src/main/java/ua/com/alevel/hw2/model/TechProduct.java
> +    public TechProduct(String model, Manufacturer manufacturer, int count, double price) {
лучше сделать protected

2022-07-18 12:21 UTC, merged